### ISSUE TITLE
Feature Request. Toggle on/off

### ISSUE THREAD

**Issue by s31teg** [ashvin-bhuttoo/PersistentHotspot#1]
Thanks for this, drives me insane having to turn on all the time.

Any chance you could make so can toggle on and off from the tray icon?

A good example is: https://www.zhornsoftware.co.uk/caffeine/

TY
S

**Comment by ashvin-bhuttoo** [comment]
Hi, glad you found PersistentHotspot useful.
I will work on the requested feature as soon as i get some free time :)

**Comment by s31teg** [comment]
Perfect. Ty!

Also this app keeps the laptop awake when closed. And the only way to close is from task manager.

Sent from iPhone
________________________________

**Comment by ashvin-bhuttoo** [comment]
Features implemented, 
Added Exit option in tray icon context menu
Added "Turn Off"/"Turn On" options in tray icon context menu

Build Version: 1.0.1
Notes: need to kill running instance of PersistantHotspot and uninstall it in add/remove programs before installing 1.0.1

**Comment by s31teg** [comment]
TY
