### ISSUE TITLE
Cannot open project type 54435603-DBB4-11D2-8724-00A0C9A8B90C in Visual Studio 2019

### ISSUE THREAD

**Issue by RobDaPraia** [ashvin-bhuttoo/PersistentHotspot#3]
HI,

thanks for this code.

Just tried to open the solution in Visual Studio 2019, but it says it cannot open the project PersistentHotspotSetup, error https://go.microsoft.com/fwlink/?LinkId=660952&projecttype=54435603-DBB4-11D2-8724-00A0C9A8B90C

When I lookup the GUID : Visual Studio 2015 Installer Project Extension -  {54435603-DBB4-11D2-8724-00A0C9A8B90C}

Can the Visual Studio 2015 Installer Project Extension be installed in Visual Studio 2019 or do you need to add another extendion to Visual Studio 2019 to read the setup project ?

**Comment by ashvin-bhuttoo** [comment]
You can use vs2019 setup project extension, it should work fine. I think mine was installshield 2015, i need to upgrade to newer vs2019 version on my dev machine.

**Comment by ashvin-bhuttoo** [comment]
Let me know if it works :wink:

**Comment by RobDaPraia** [comment]
Thanks, 

have not tried it yet, deployed it manually

**Comment by thcedi** [comment]
I had the same problem today, you can just use the VS2019 setup project extensions, it works fine.
