### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Horozor** [ashvin-bhuttoo/PersistentHotspot#5]
Hi. When i try install your programm it alwasy give me error
What should i do?
1.0.3 ver.
![Аннотация 2020-05-26 201913](https://user-images.githubusercontent.com/37561569/82930597-4fba4000-9f8e-11ea-8f9a-9b96ca95b01f.jpg)

**Comment by ashvin-bhuttoo** [comment]
Im not sure why you are getting this, are you running windows 10 ?

**Comment by Horozor** [comment]
@ashvin-bhuttoo Yes, Windows 10 1909

**Comment by ashvin-bhuttoo** [comment]
@Horozor Did you get run as administrator prompt ? If not can you try with  [UAC disabled](https://kb.netwrix.com/663) ?

**Comment by Horozor** [comment]
@ashvin-bhuttoo 
I think I solved the problem, I just got the files from the installer using the total commander, and the program works

**Comment by ashvin-bhuttoo** [comment]
Ok ;-)
