### ISSUE TITLE
Is there a way to set the "Share my Internet connection over" to "Bluetooth" instead of "WI-FI"?

### ISSUE THREAD

**Issue by seanzcan** [ashvin-bhuttoo/PersistentHotspot#7]
Thanks for the project, it works great, but when it turns on the mobile hotspot, the "Share my Internet connection over" in Mobile hotspot is switched to "WI-FI", and is it possible to set to "Bluetooth"?

**Comment by ashvin-bhuttoo** [comment]
hi, i have never tried bluetooth, i will need to check if i am able to programmatically set the connection type to bluetooth

**Comment by ashvin-bhuttoo** [comment]
I am pretty sure this is not possible on windows 10, sorry.
